import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Custom MCP Node.js Project",
  description: "Custom MCP Node.js Project — generated by AI Project Builder",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
