import Link from "next/link";

export default function HomePage() {
  return (
    <main className="mx-auto max-w-2xl p-8">
      <h1 className="text-3xl font-bold">Custom MCP Node.js Project</h1>
      <p className="mt-2 text-gray-600">
        Generated by the AI Project Builder from reusable base modules.
      </p>
      <h2 className="mt-8 text-xl font-semibold">Available routes</h2>
      <ul className="mt-3 list-disc space-y-2 pl-6">
          <li>
            <Link className="text-blue-600 underline" href="/example">
              Example
            </Link>
          </li>
      </ul>
    </main>
  );
}
